version: '3'

services:
  node:
    tty: true
    stdin_open: true
    container_name: loyalty-api
    depends_on:
      - postgres
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/code'
      - '/code/node_modules'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pass123
    ports:
      - '5432:5432'
